import img1 from '../images/img1.jpg'
import img2 from '../images/img2.jpg'
import img3 from '../images/img3.jpg'
import img4 from '../images/img4.jpg'
import img5 from '../images/img5.jpg'


export const emailTemplateData = [
  {
    title: "Feature Services",
    tag:"announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img1,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    title: "Weekely Newsletter",
    tag:"announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img2,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    title: "Editorial Newsletter",
    tag:"announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img3,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    title: "New Product Launch",
    tag:"announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img4,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    title: "New Services",
    tag:"announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img5,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    title: "Feature Editorial Newsletter",
    tag:"educate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img4,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    title: "New Services",
    tag:"educate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img2,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    title: "Weekely Newsletter",
    tag:"educate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img5,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    title: "New Product Launch",
    tag:"educate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img1,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    title: "Feature Services",
    tag:"educate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img3,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    title: "New Services",
    tag:"invitation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img5,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    title: "Weekely Newsletter",
    tag:"invitation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img2,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    title: "Feature Editorial Newsletter",
    tag:"invitation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img4,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    title: "Feature Services",
    tag:"invitation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img3,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    title: "New Product Launch",
    tag:"invitation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img1,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    title: "Weekely Newsletter",
    tag:"occation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img5,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    title: "Feature Services",
    tag:"occation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img4,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    title: "New Product Launch",
    tag:"occation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img3,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    title: "New Services",
    tag:"occation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img2,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    title: "Feature Editorial Newsletter",
    tag:"occation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img1,
    isPopular:true,
    createdAt: 1115211422,
  },
];
