import img1 from '../images/img1.jpg'
import img2 from '../images/img2.jpg'
import img3 from '../images/img3.jpg'
import img4 from '../images/img4.jpg'
import img5 from '../images/img5.jpg'


export const emailTemplateData = [
  {
    id:'1',
    title: "Feature Services",
    tag:"announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img1,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    id:'2',
    title: "Weekely Newsletter",
    tag:"announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img2,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    id:'3',
    title: "Editorial Newsletter",
    tag:"announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img3,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    id:'4',
    title: "New Product Launch",
    tag:"announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img4,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    id:'5',
    title: "New Services",
    tag:"announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img5,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    id:'6',
    title: "Feature Editorial Newsletter",
    tag:"educate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img4,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    id:'7',
    title: "New Services",
    tag:"educate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img2,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    id:'8',
    title: "Weekely Newsletter",
    tag:"educate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img5,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    id:'9',
    title: "New Product Launch",
    tag:"educate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img1,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    id:'10',
    title: "Feature Services",
    tag:"educate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img3,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    id:'11',
    title: "New Services",
    tag:"invitation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img5,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    id:'12',
    title: "Weekely Newsletter",
    tag:"invitation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img2,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    id:'13',
    title: "Feature Editorial Newsletter",
    tag:"invitation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img4,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    id:'14',
    title: "Feature Services",
    tag:"invitation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img3,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    id:'15',
    title: "New Product Launch",
    tag:"invitation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img1,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    id:'16',
    title: "Weekely Newsletter",
    tag:"occation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img5,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    id:'17',
    title: "Feature Services",
    tag:"occation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img4,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    id:'18',
    title: "New Product Launch",
    tag:"occation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img3,
    isPopular:true,
    createdAt: 1115211422,
  },
  {
    id:'19',
    title: "New Services",
    tag:"occation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img2,
    isPopular:false,
    createdAt: 1115211422,
  },
  {
    id:'20',
    title: "Feature Editorial Newsletter",
    tag:"occation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    imageUrl:img1,
    isPopular:true,
    createdAt: 1115211422,
  },
];
